# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60abbcec2b9407a3199761fa87c58490dfe4c9100c3019f9e776ccfc4d73540d7df2c4ad186a77297a6f55618efdf6919359f6a0d70307ecc81dbfe412818baf

test:
  secret_key_base: d95162ea4d25583fc37fc45ea2ac67f00fa77ec747029e6871406c839ae89cee4fee57a9d4d346e4580fb5129d58e8d2d33cf98c7ae9770c487256494753d29a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
